AC_DEFUN_ONCE([SETUP_BINARIES_EXTENSIONS],
[
  LIBRARY_PREFIX=lib
  SHARED_LIBRARY='lib[$]1.so'
  STATIC_LIBRARY='lib[$]1.a'
  SHARED_LIBRARY_SUFFIX='.so'
  STATIC_LIBRARY_SUFFIX='.a'
  OBJ_SUFFIX='.o'
  EXE_SUFFIX=''

  AC_SUBST(OBJ_SUFFIX)
  AC_SUBST(SHARED_LIBRARY)
  AC_SUBST(STATIC_LIBRARY)
  AC_SUBST(LIBRARY_PREFIX)
  AC_SUBST(SHARED_LIBRARY_SUFFIX)
  AC_SUBST(STATIC_LIBRARY_SUFFIX)
  AC_SUBST(EXE_SUFFIX)
])
